name: "build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/diffcheckorg/diffcheck-windows:latest

  configure-and-build:
    needs: build-container
    runs-on: windows-latest
    container:
      image: ghcr.io/diffcheckorg/diffcheck-windows:latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: