name: "cpp-build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


env:
  BUILD_TYPE: Release
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Setup conda environment
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     auto-update-conda: true
      #     python-version: 3.9.1

      - name: Cmake Configure
        run: |
          cd ${{github.workspace}}/src/diffCheck
          mkdir build
          cmake -S . -B build -A x64 -DBUILD_PYTHON_MODULE=OFF

      - name: CMake Build
        run: ${{github.workspace}}/cmake/build.bat