name: "pypi-build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


env:
  BUILD_TYPE: Release
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  pypi_build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9.1

      - name: Cmake Configure
        run: ${{github.workspace}}/cmake/config.bat
      - name: CMake Build
        run: ${{github.workspace}}/cmake/build.bat

      - name: Install CPython
        run: |
          choco install python --version=3.9.10

      - name: Build wheel
        run: |
          cd src/gh/diffCheck/
          python setup.py bdist_wheel
          cd ../../..

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: src/gh/diffCheck/dist/