name: "test-pass"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  windows:
    runs-on: windows-latest

    env:
      BUILD_TYPE: Release
      VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake
      DF_TEST_DATA_DIR: ${{ github.workspace }}/tests/test_data

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9.1

      - name: Create diff_check conda environment
        run: conda env create -f environment.yml
      
      - name: Activate diff_check conda environment
        run: conda activate diff_check

      - name: Verify Python version
        run: conda run --name diff_check --no-capture-output python --version

      - name: Cmake Configure
        run: |
          conda run --name diff_check --no-capture-output cmake -S . -B build -A x64 -DBUILD_PYTHON_MODULE=ON -DBUILD_TESTS=ON -DRUN_TESTS=OFF

      - name: CMake Build
        run: conda run --name diff_check --no-capture-output cmake --build build --config Release

      # TODO: debug
      - name: List the files in the bin cpp
        run: |
          ls ${{github.workspace}}/build/bin/Release

      # TODO: debug
      - name: List the files in the bin pybinds
        run: |
          ls ${{github.workspace}}/build/Release

      - name: Copying the dlls
        run: |
          cp ${{github.workspace}}/build/bin/Release/diffCheck.dll ${{github.workspace}}/tests/integration_tests/pybinds_tests
          cp ${{github.workspace}}/build/bin/Release/Open3D.dll ${{github.workspace}}/tests/integration_tests/pybinds_tests
          cp ${{github.workspace}}/build/Release/*.pyd ${{github.workspace}}/tests/integration_tests/pybinds_tests

      # TODO: debug
      - name: test if the dlls are copied
        run: |
          ls ${{github.workspace}}/tests/integration_tests/pybinds_tests

      - name: Run tests with cmake
        run: |
          cd build/
          conda run --name diff_check --no-capture-output ctest -C Release --verbose --output-on-failure