name: "test-pass"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


env:
  BUILD_TYPE: Release
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9.1

      - name: Create diff_check conda environment
        run: conda env create -f environment.yml
      
      - name: Activate diff_check conda environment
        run: conda activate diff_check

      - name: Verify Python version
        run: conda run --name diff_check python --version

      - name: Cmake Configure
        run: |
          conda run --name diff_check cmake -S . -B build -A x64 -DBUILD_PYTHON_MODULE=ON -DBUILD_TESTS=ON -DRUN_TESTS=OFF

      - name: CMake Build
        run: conda run --name diff_check cmake --build build --config Release

      - name: Copying the dlls
        run: |
          cp build/bin/Release/diffCheck.dll tests/integration_tests/pybinds_tests
          cp build/bin/Release/Open3D.dll tests/integration_tests/pybinds_tests
          cp build/Release/*.pyd tests/integration_tests/pybinds_tests

      - name: Run tests with cmake
        run: |
          cd build/
          conda run --name diff_check ctest -C Release --verbose