name: "win-build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



env:
  BUILD_TYPE: Release
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: CMAKE Configure
        run: >
          cmake -B ${{github.workspace}}/build -S ${{github.workspace}} 
          -D CMAKE_BUILD_TYPE=Release
      - name: CMake Build
        run: cmake --build ${{github.workspace}}/build --config Release